# fly.toml app configuration file generated for rails-store on 2023-06-02T09:12:58-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "rails-store"
primary_region = "mia"
console_command = "/rails/bin/rails console"

[http_service]
  processes = ["app"]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0

[[statics]]
  guest_path = "/rails/public"
  url_prefix = "/"

[processes]
app = "bin/rails server"
worker = "bundle exec sidekiq"